version: 1.5.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack CoreHelpers.Azure.Worker.nuspec -Version %APPVEYOR_BUILD_VERSION% -Verbosity detailed
test: off
artifacts:
- path: '*.nupkg'
  name: NuGet Packages
